update roadSegment with 2 attributes
smart-data-models/dataModel.Transportation pull request #15
Opened 2022-01-11 14:05 UTC by gvdwouwer

I have added status and statusDescription to allow modelling a piece of road that runs over a bridge or lock. When the bridge is raised, no traffic is temporarily possible on the roadsegment. The attributes could also be used to model other types of events (such as roadworks) that temporarily limit or prohibit traffic.

2022-01-12 12:17 UTC, albertoabellagarcia requested changes
Thank you for the contribution
1) I need you to extend the example with the values for the new attributes. files in the examples' directory
2) Needs the word 'Property. ' in the descriptions of the attributes according to the [contribution manual](https:/bit.ly/contribution_manual)
3) It is also required to accept the [contribution agreement](https://smartdatamodels.org/index.php/contributor-agreement/)
4) if you want to appear listed in the [contributors](https://github.com/smart-data-models/dataModel.Transportation/blob/master/CONTRIBUTORS.yaml) modify the PR accordingly
5) Please also extend the [adopters.yaml](https://github.com/smart-data-models/dataModel.Transportation/blob/master/RoadSegment/ADOPTERS.yaml) file with the use case

2022-01-13 11:14 UTC, gvdwouwer commented
I have made these changes and pushed them to github: 
* added Property to the description in schema.json
* adopters.yaml updated
* accepted the contribution agreement
* The examples are updated. However, for the LD examples, I think the normalised and the key-value example has been switched in the original repo. Please advise if that should be corrected.

I would like to be listed as a contributer as you mentioned in your 4th item. But I do not know how I should modify the PR.

2022-01-13 14:35 UTC, albertoabellagarcia reviewed
Attend the minor issues and ready to be published. don't you want to appear at the contributors.yaml file?

2022-01-13 14:35 UTC, albertoabellagarcia commented on RoadSegment/examples/example.jsonld
> -    "id": "urn:ngsi-ld:RoadSegment:Spain-RoadSegment-A62-osm-24702186",
it should be example-normalized.jsonld

2022-01-17 12:13 UTC, gvdwouwer commented on RoadSegment/examples/example-geojsonfeature.json
> -  "id": "urn:ngsi-ld:RoadSegment:Spain-RoadSegment-A62-osm-24702186",
reverted example-geojsonfeature.json to the original file

2022-01-17 12:13 UTC, gvdwouwer commented on RoadSegment/examples/example-normalized.jsonld
> -    "id": "urn:ngsi-ld:RoadSegment:Spain-RoadSegment-A62-osm-24702186",
done

2022-01-17 12:14 UTC, gvdwouwer commented on RoadSegment/schema.json
> +	"$schemaVersion": "0.2.0",
done

2022-01-17 13:19 UTC, albertoabellagarcia commented
Ready to be published

2022-01-17 13:19 UTC, merged